source 'https://rubygems.org'

gem 'rails', '3.2.3'

gem 'mysql2'
gem 'json'

group :assets do
  gem 'sass-rails', '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'therubyracer'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'rails-i18n'
gem 'andand'
gem 'memcache-client'
gem 'mini_record'
gem 'slim'
gem 'cancan'
gem 'less-rails-bootstrap'
gem 'formtastic', :git => 'git://github.com/justinfrench/formtastic.git', :branch => '2.1-stable'
gem 'formtastic-bootstrap', :git => 'git://github.com/cgunther/formtastic-bootstrap.git', :branch => 'bootstrap2-rails3-2-formtastic-2-1'
gem 'will_paginate'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
gem 'fb_graph'
gem 'geocoder'
gem 'gmaps4rails', '1.4.5'
gem 'railhead_autouser'
gem 'railhead_permalink'
gem 'paperclip', '~> 2.7'
gem 'oink'
gem 'paper_trail'
gem 'globalize3'
gem 'later_dude'
gem 'rails_autolink'
gem 'exception_notification'
