#!/bin/bash

rsync -rptzL --stats --progress --exclude-from=`dirname $_`/stage.exclude -e 'ssh -p 30000' . nagybence@tipogral.hu:/var/www/get2gather
ssh -p 30000 nagybence@tipogral.hu /var/www/get2gather/script/restart
